config/routes.rb
C5devV5::Application.routes.draw do
  devise_for :businesses
  get "welcome/index"
  get "welcome/about"
  get "welcome/contact"
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  
    devise_scope :business do
      get 'register', to: 'devise/registrations#new', as: :businessregister
      get 'login', to: 'devise/sessions#new', as: :businesslogin
      get 'logout', to: 'devise/sessions#destroy', as: :businesslogout
  end
  get '/:id', to: 'profiles#show'
  root 'welcome#index'

  

end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :address, :city, :state, :zip, :phone, :image, :email, :password, :password_confirmation,) }
      devise_parameter_sanitizer.for(:edit) { |u| u.permit(:name, :address, :city, :state, :zip, :phone, :image, :email, :password, :password_confirmation,) }
  end
    private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @businesses = Business.all
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
        def flash_class(type)
    case type 
    when :alert
      "alert-error"
    when :notice
      "alert-success"
    else
      ""
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>C5devV5</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
   <nav class="navbar navbar-custom navbar-static-top" role="navigation">
           <div class ="container">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#nav-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="glyphicon glyphicon-star" style="color:white"></span>
    </button>
    <a class="navbar-brand" href="/">C5</a>
  </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="nav-collapse">
    <ul class="nav navbar-nav">
      <li class="active"><%= link_to "About", welcome_about_path %></li>
      <li><%= link_to "Contact", welcome_contact_path %></li>
    </ul>
    <form class="navbar-form navbar-left" role="search">
      <div class="form-group">
        <input type="text" class="form-control" placeholder="Search">
      </div>
      <button type="submit" class="btn btn-default">Submit</button>
    </form>
    <ul class="nav navbar-nav navbar-right">
      <%if business_signed_in? %>
        <li><%= link_to current_business.name, edit_business_registration_path %></li>
        <li><%= link_to "Log Out", businesslogout_path %></li>
      <% else %>
<div id="user-widget">
  <% if current_user %>
    Welcome <strong><%= current_user.name %></strong>!
    <%= link_to "Sign out", signout_path, id: "sign_out" %>
  <% else %>
    <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
  <% end %>
</div>
      <% end %>
    </ul>
             </div>
  </div><!-- /.navbar-collapse -->
</nav>
      <div class ="container">
      <% flash.each do |type, message| %>
        <div class="alert <%= flash_class type %>">
          <button class="close" data-dismiss="alert">x</button>
        <%= message %>
      </div>
    <% end %>
<%= yield %>
  </div>
</body>
</html>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/contact.html.erb
<h1>Welcome#contact</h1>
<p>Find me in app/views/welcome/contact.html.erb</p>

app/views/welcome/index.html.erb
<p align="center">
<%= image_tag("c5banner.png", :alt => "banner") %>
</p>
<% @businesses.each do |business|%>
<%= link_to image_tag(business.image_url(:thumb).to_s), profiles_show_path(id: business.name) %>
<% end %>